
export enum VoiceName {
  Kore = 'Kore',
  Puck = 'Puck',
  Charon = 'Charon',
  Fenrir = 'Fenrir',
  Zephyr = 'Zephyr',
}

export enum ToneType {
  Neutral = 'Neutral',
  Excited = 'Excited',
  Professional = 'Professional',
  Soothing = 'Soothing',
  Dramatic = 'Dramatic',
  Sales = 'Sales (Black Friday)',
  Preaching = 'Preaching'
}

export enum AppMode {
  Home = 'Home',
  Narration = 'Narration',
  Music = 'Music',
  Avatar = 'Avatar',
  SFX = 'SFX',
  SmartPlayer = 'SmartPlayer',
  Manga = 'Manga',
  Admin = 'Admin'
}

export interface AudioItem {
  id: string;
  text: string;
  voice: VoiceName;
  audioData: AudioBuffer; // Decoded audio buffer for playback
  createdAt: Date;
  duration: number;
}

export interface MusicItem {
  id: string;
  title: string;
  style: string;
  lyrics: string; // Generated by Gemini or "Instrumental"
  coverColor: string; // CSS gradient string
  audioData: AudioBuffer; // Procedurally generated instrumental
  createdAt: Date;
  duration: number;
  isRemix?: boolean; // New flag for remixed tracks
  engine?: 'web-audio' | 'musicgen';
}

export interface SFXItem {
  id: string;
  name: string;
  type: string;
  audioData: AudioBuffer;
  createdAt: Date;
}

export interface AvatarProject {
  id: string;
  imageUrl: string;
  audioData: AudioBuffer;
  name: string;
}

export interface ProcessingState {
  isEnhancing: boolean;
  isGeneratingAudio: boolean;
  error: string | null;
}

// --- Manga / Gibi Types ---

export type ComicStyle = 'Manga' | 'American Comic' | 'Pixar 3D' | 'Anime' | 'Sketch';

export interface ComicPage {
  id: string;
  imageUrl: string; // Base64
  text: string;
  audioData?: AudioBuffer; // Optional Narration
  panelNumber: number;
}

export interface ComicProject {
  id: string;
  title: string;
  style: ComicStyle;
  pages: ComicPage[];
  characterImage?: string; // Base64 reference
}

// --- Monetization Types ---

export type UserPlan = 'free' | 'premium';

export interface UserStatus {
  plan: UserPlan;
  expiryDate: number | null; // Timestamp
  narrationsToday: number;
}

export interface PremiumCode {
  code: string;
  days: number;
  isRedeemed: boolean;
  createdAt: number;
  redeemedAt?: number;
}
